### ISSUE TITLE
About using the code and references

### ISSUE THREAD

**Issue by lyysl** [gmrandazzo/DeepMatrixInversion#1]
I want to ask is there an instruction how to use this code? Also, is there a research paper for this work?
I would like to use for solving the matrix inverse problem for a large matrix system. Is it possible?
Thank you!

**Comment by gmrandazzo** [comment]
Hi Please have a look to the latest version of this package. 

There is no paper...the paper is the README.

It works good for 3x3 matrix... never tested for larger matrix... you can give a try and also modify the network with a better one. Instructions on how to use this should be now clear. Let me know if you still have issues.
